const presets = [
  {
    type: 'rotary',
    phase: 'open',
    rotaryType: 'concurrent',
    xFreq: '7',
    yFreq: '3',
    rotaryFreq: '2.001',
    rotaryAmp: 1,
    speed: '30.75',
    decay: '0',
    fade: '0.06',
    lineWidth: '0.07',
    size: '0.95'
  },
  {
    type: 'rotary',
    phase: 'open',
    rotaryType: 'concurrent',
    xFreq: '2',
    yFreq: '2',
    rotaryFreq: '3',
    rotaryAmp: '0.67',
    speed: '100',
    decay: '0.02',
    fade: '0.02',
    lineWidth: '0.11',
    size: '1.11'
  },
  {
    type: 'rotary',
    phase: 'closed',
    rotaryType: 'concurrent',
    xFreq: '2.002',
    yFreq: '1',
    rotaryFreq: '1.001',
    rotaryAmp: '0.45',
    speed: '100',
    decay: '0',
    fade: '0.06',
    lineWidth: '0.25',
    size: '1.16'
  },
  {
    type: 'lateral',
    phase: 'open',
    rotaryType: 'concurrent',
    xFreq: '1.24',
    yFreq: '1.24',
    rotaryFreq: '0.001',
    rotaryAmp: 1,
    speed: '1.06',
    decay: '1.52',
    fade: '1.04',
    lineWidth: '1.79',
    size: '1.98'
  },
  {
    type: 'rotary',
    phase: 'open',
    rotaryType: 'countercurrent',
    xFreq: '2',
    yFreq: '2',
    rotaryFreq: '3.01',
    rotaryAmp: '0.53',
    speed: '1.88',
    decay: '0.41',
    fade: '0.59',
    lineWidth: '1.25',
    size: '1.26'
  },
  {
    type: 'rotary',
    phase: 'open',
    rotaryType: 'concurrent',
    xFreq: 2,
    yFreq: '3',
    rotaryFreq: '0.001',
    rotaryAmp: 1,
    speed: '100',
    decay: '0',
    fade: '0.02',
    lineWidth: '0.07',
    size: '0.95'
  },
  {
    type: 'rotary',
    phase: 'open',
    rotaryType: 'countercurrent',
    xFreq: '2',
    yFreq: '2',
    rotaryFreq: '6.001',
    rotaryAmp: '0.75',
    speed: '96.59',
    decay: '0.02',
    fade: '0.03',
    lineWidth: '0.09',
    size: '1.33'
  },
  {
    type: 'rotary',
    phase: 'open',
    rotaryType: 'countercurrent',
    xFreq: '2',
    yFreq: '2',
    rotaryFreq: '10.33',
    rotaryAmp: '0.19',
    speed: '0.09',
    decay: '0.04',
    fade: '0.06',
    lineWidth: '1.25',
    size: '1.58'
  },
  {
    type: 'lateral',
    phase: 'closed',
    rotaryType: 'countercurrent',
    xFreq: '4',
    yFreq: '3',
    rotaryFreq: 5,
    rotaryAmp: 1,
    speed: '0.08',
    decay: 0,
    fade: '2',
    lineWidth: '2.35',
    size: '1.63'
  },
  {
    type: 'rotary',
    phase: 'open',
    rotaryType: 'countercurrent',
    xFreq: 2,
    yFreq: 2,
    rotaryFreq: 3.02,
    rotaryAmp: 0.33,
    speed: '0.53',
    decay: '0.45',
    fade: '0.2',
    lineWidth: 0.8,
    size: '1.48'
  },
  {
    type: 'rotary',
    phase: 'open',
    rotaryType: 'concurrent',
    xFreq: '2.001',
    yFreq: '2.001',
    rotaryFreq: '16',
    rotaryAmp: '0.125',
    speed: '49.76',
    decay: '0.25',
    fade: '0.11',
    lineWidth: '0.49',
    size: '1.7'
  },
  {
    type: 'rotary',
    phase: 'open',
    rotaryType: 'concurrent',
    xFreq: '5.29',
    yFreq: '5.29',
    rotaryFreq: '0.001',
    rotaryAmp: 1,
    speed: '100',
    decay: '0.005',
    fade: '0.005',
    lineWidth: '0.03',
    size: 1
  },
  {
    type: 'rotary',
    phase: 'open',
    rotaryType: 'countercurrent',
    xFreq: '4',
    yFreq: '4',
    rotaryFreq: '5.001',
    rotaryAmp: 0.2,
    speed: '84.86',
    decay: '0.03',
    fade: '0.02',
    lineWidth: '0.06',
    size: '1.63'
  },
  {
    type: 'rotary',
    phase: 'open',
    rotaryType: 'countercurrent',
    xFreq: '2',
    yFreq: '2',
    rotaryFreq: '1.999',
    rotaryAmp: 0.5,
    speed: '92.84',
    decay: '0.01',
    fade: '0.02',
    lineWidth: '0.16',
    size: '1.28'
  },
  {
    type: 'rotary',
    phase: 'open',
    rotaryType: 'countercurrent',
    xFreq: 2,
    yFreq: 2,
    rotaryFreq: 3.02,
    rotaryAmp: 0.33,
    speed: '15',
    decay: '0.45',
    fade: '0.2',
    lineWidth: 0.8,
    size: '1.48'
  },
  {
    type: 'lateral',
    phase: 'closed',
    rotaryType: 'countercurrent',
    xFreq: '4',
    yFreq: '5.001',
    rotaryFreq: 3,
    rotaryAmp: 1,
    speed: '83.1',
    decay: '0.04',
    fade: '0.06',
    lineWidth: '0.15',
    size: '1.64'
  },
  {
    type: 'rotary',
    phase: 'open',
    rotaryType: 'concurrent',
    xFreq: '7',
    yFreq: '3.001',
    rotaryFreq: '5',
    rotaryAmp: '2.8',
    speed: '45.89',
    decay: '0',
    fade: '0.1',
    lineWidth: '0.07',
    size: '0.45'
  },
  {
    type: 'rotary',
    phase: 'open',
    rotaryType: 'countercurrent',
    xFreq: '3',
    yFreq: '3',
    rotaryFreq: '4',
    rotaryAmp: 1,
    speed: '0.06',
    decay: 0,
    fade: '2',
    lineWidth: '1.71',
    size: '0.96'
  },
  {
    type: 'rotary',
    phase: 'open',
    rotaryType: 'concurrent',
    xFreq: 2,
    yFreq: 2,
    rotaryFreq: '2.001',
    rotaryAmp: 1,
    speed: '100',
    decay: '0.015',
    fade: '0.015',
    lineWidth: '0.12',
    size: 1
  },
  {
    type: 'rotary',
    phase: 'closed',
    rotaryType: 'concurrent',
    xFreq: 2,
    yFreq: '3',
    rotaryFreq: '0.001',
    rotaryAmp: 1,
    speed: '83.27',
    decay: '0.01',
    fade: '0.02',
    lineWidth: '0.13',
    size: 1
  },
  {
    type: 'rotary',
    phase: 'open',
    rotaryType: 'concurrent',
    xFreq: '7',
    yFreq: '11.001',
    rotaryFreq: '5',
    rotaryAmp: '0.85',
    speed: '19.83',
    decay: '0',
    fade: '0.13',
    lineWidth: '0.07',
    size: '0.95'
  },
  {
    type: 'rotary',
    phase: 'open',
    rotaryType: 'concurrent',
    xFreq: '8',
    yFreq: '8',
    rotaryFreq: '9',
    rotaryAmp: 1,
    speed: '0.04',
    decay: 0,
    fade: '2',
    lineWidth: '1.86',
    size: 1
  },
  {
    type: 'rotary',
    phase: 'open',
    rotaryType: 'concurrent',
    xFreq: '2',
    yFreq: '2',
    rotaryFreq: '16',
    rotaryAmp: '0.125',
    speed: '0.08',
    decay: '0',
    fade: '22',
    lineWidth: '2.04',
    size: '1.61'
  },
  {
    type: 'rotary',
    phase: 'open',
    rotaryType: 'countercurrent',
    xFreq: '11',
    yFreq: '11',
    rotaryFreq: '12',
    rotaryAmp: 1,
    speed: '0.09',
    decay: '0',
    fade: '10',
    lineWidth: '0.73',
    size: 1
  },
  {
    type: 'lateral',
    phase: 'open',
    rotaryType: 'countercurrent',
    xFreq: '2',
    yFreq: '3.0001',
    rotaryFreq: 5,
    rotaryAmp: 1,
    speed: '63.56',
    decay: 0,
    fade: '0.16',
    lineWidth: '0.4',
    size: '1.63'
  },
  {
    type: 'rotary',
    phase: 'open',
    rotaryType: 'concurrent',
    xFreq: 2,
    yFreq: 2,
    rotaryFreq: '3',
    rotaryAmp: 1,
    speed: '100',
    decay: '0.03',
    fade: '0.001',
    lineWidth: '0.08',
    size: 1
  },
  {
    type: 'rotary',
    phase: 'open',
    rotaryType: 'concurrent',
    xFreq: '2',
    yFreq: '1',
    rotaryFreq: '0.001',
    rotaryAmp: '2.95',
    speed: '100',
    decay: '0.04',
    fade: '0.02',
    lineWidth: '0.25',
    size: '0.52'
  },
  {
    type: 'rotary',
    phase: 'open',
    rotaryType: 'countercurrent',
    xFreq: '4',
    yFreq: '4',
    rotaryFreq: '5.001',
    rotaryAmp: 1,
    speed: '50.7',
    decay: '0',
    fade: '0.2',
    lineWidth: '0.32',
    size: 1
  },
  {
    type: 'rotary',
    phase: 'open',
    rotaryType: 'countercurrent',
    xFreq: '4',
    yFreq: '4',
    rotaryFreq: '5.01',
    rotaryAmp: 0.2,
    speed: '2.29',
    decay: 0,
    fade: '1.2',
    lineWidth: '0.34',
    size: '1.63'
  },
  {
    type: 'rotary',
    phase: 'closed',
    rotaryType: 'concurrent',
    xFreq: '1',
    yFreq: '1',
    rotaryFreq: '1.0005',
    rotaryAmp: 1,
    speed: '100',
    decay: 0,
    fade: '0.02',
    lineWidth: '0.12',
    size: 1
  },
  {
    type: 'lateral',
    phase: 'open',
    rotaryType: 'concurrent',
    xFreq: '5.82',
    yFreq: '5.82',
    rotaryFreq: '0.001',
    rotaryAmp: 1,
    speed: '100',
    decay: '0.16',
    fade: '0.02',
    lineWidth: '0.18',
    size: '1.85'
  },
  {
    type: 'rotary',
    phase: 'open',
    rotaryType: 'concurrent',
    xFreq: 2,
    yFreq: '4',
    rotaryFreq: '2.005',
    rotaryAmp: 1,
    speed: '18.31',
    decay: '0.02',
    fade: '0.32',
    lineWidth: 0.8,
    size: 1
  },
  {
    type: 'lateral',
    phase: 'open',
    rotaryType: 'concurrent',
    xFreq: '3',
    yFreq: 3.0004,
    rotaryFreq: 3,
    rotaryAmp: 1,
    speed: '100',
    decay: '0.01',
    fade: '0.01',
    lineWidth: '0.06',
    size: '1.86'
  },
  {
    type: 'rotary',
    phase: 'open',
    rotaryType: 'countercurrent',
    xFreq: '4',
    yFreq: '4',
    rotaryFreq: '5.001',
    rotaryAmp: 1,
    speed: '100',
    decay: '0.04',
    fade: '0.06',
    lineWidth: '0.07',
    size: 1
  },
  {
    type: 'rotary',
    phase: 'open',
    rotaryType: 'countercurrent',
    xFreq: '3',
    yFreq: '3',
    rotaryFreq: '4.001',
    rotaryAmp: '0.75',
    speed: '65.61',
    decay: '0.04',
    fade: '0.06',
    lineWidth: '0.12',
    size: '1.12'
  }
];
