const presets = [
  {
    type: 'lateral',
    phase: 'closed',
    rotaryType: 'countercurrent',
    integerLock: true,
    xyLock: false,
    xFreq: '4',
    yFreq: '5.001',
    rotaryFreq: 3,
    invert: true,
    speed: '83.1',
    decay: '0.04',
    fade: '0.06',
    lineWidth: '0.15',
    size: '1.64',
    darkMode: false
  },
  {
    type: 'rotary',
    phase: 'open',
    rotaryType: 'countercurrent',
    integerLock: false,
    xyLock: true,
    xFreq: '4',
    yFreq: '4',
    rotaryFreq: '5.001',
    invert: false,
    speed: '50.7',
    decay: '0',
    fade: '0.2',
    lineWidth: '0.32',
    size: 1,
    darkMode: false
  },
  {
    type: 'rotary',
    phase: 'open',
    rotaryType: 'countercurrent',
    integerLock: false,
    xyLock: true,
    xFreq: '4',
    yFreq: '4',
    rotaryFreq: '5.001',
    invert: false,
    speed: '100',
    decay: '0.04',
    fade: '0.06',
    lineWidth: '0.07',
    size: 1,
    darkMode: false
  },
  {
    type: 'rotary',
    phase: 'open',
    rotaryType: 'countercurrent',
    integerLock: false,
    xyLock: true,
    xFreq: '4',
    yFreq: '4',
    rotaryFreq: '5.01',
    invert: true,
    speed: '2.29',
    decay: 0,
    fade: '1.2',
    lineWidth: '0.34',
    size: '1.63',
    darkMode: false
  },
  {
    type: 'rotary',
    phase: 'open',
    rotaryType: 'countercurrent',
    integerLock: false,
    xyLock: true,
    xFreq: '4',
    yFreq: '4',
    rotaryFreq: '5.001',
    invert: true,
    speed: '84.86',
    decay: '0.03',
    fade: '0.02',
    lineWidth: '0.06',
    size: '1.63',
    darkMode: false
  },
  {
    type: 'lateral',
    phase: 'closed',
    rotaryType: 'countercurrent',
    integerLock: true,
    xyLock: false,
    xFreq: '4',
    yFreq: '3',
    rotaryFreq: 5,
    invert: true,
    speed: '0.08',
    decay: 0,
    fade: '2',
    lineWidth: '2.35',
    size: '1.63',
    darkMode: false
  },
  {
    type: 'rotary',
    phase: 'closed',
    rotaryType: 'concurrent',
    integerLock: false,
    xyLock: false,
    xFreq: 2,
    yFreq: '3',
    rotaryFreq: '0.001',
    invert: false,
    speed: '83.27',
    decay: '0.01',
    fade: '0.02',
    lineWidth: '0.13',
    size: 1,
    darkMode: false
  },
  {
    type: 'rotary',
    phase: 'open',
    rotaryType: 'concurrent',
    integerLock: false,
    xyLock: false,
    xFreq: 2,
    yFreq: 2,
    rotaryFreq: '3',
    invert: false,
    speed: '100',
    decay: '0.03',
    fade: '0.001',
    lineWidth: '0.08',
    size: 1,
    darkMode: false
  },
  {
    type: 'rotary',
    phase: 'open',
    rotaryType: 'concurrent',
    integerLock: true,
    xyLock: false,
    xFreq: 2,
    yFreq: '4',
    rotaryFreq: '2.005',
    invert: false,
    speed: '18.31',
    decay: '0.02',
    fade: '0.32',
    lineWidth: 0.8,
    size: 1,
    darkMode: false
  },
  {
    type: 'rotary',
    phase: 'open',
    rotaryType: 'countercurrent',
    integerLock: true,
    xyLock: true,
    xFreq: '3',
    yFreq: '3',
    rotaryFreq: '4',
    invert: false,
    speed: '0.06',
    decay: 0,
    fade: '2',
    lineWidth: '1.71',
    size: '0.96',
    darkMode: false
  }
];
